Выполнены все задания, согласно 14-го спринта.
dsiberia9s/iOS-TrackerApp-Public pull request #1
Opened 2023-10-19 11:55 UTC by dsiberia9s

2023-10-19 16:16 UTC, protos17 requested changes

2023-10-19 16:16 UTC, protos17 commented on Tracker/NewHabitViewController.swift
> +        return settings.count
При возвращении значения в одну строку можно не писать return

2023-10-19 16:16 UTC, protos17 commented on Tracker/ScheduleViewController.swift
> +    var switchesState = [Bool](repeating: false, count: 7)
Рекомендую указать как private

2023-10-19 16:16 UTC, protos17 commented on Tracker/ScheduleViewController.swift
> +    @objc func doneButtonTapped() {
Тоже стоит указать как private

2023-10-19 16:16 UTC, protos17 commented on Tracker/StatisticsViewController.swift
> +class StatisticsViewController: UIViewController {
Класс лучше сразу указать как final

2023-10-19 16:16 UTC, protos17 commented on Tracker/TrackerUIViewCollectionCell.swift
> +class TrackerUIViewCollectionCell: UICollectionViewCell {
Тоже рекомендую указать как final

2023-10-19 16:16 UTC, protos17 commented on Tracker/TrackersViewController.swift
> +    var completedTrackers: [TrackerRecord] = []
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, когда они используются только внутри области объявления.

2023-10-21 11:45 UTC, protos17 requested changes

2023-10-21 11:45 UTC, protos17 commented on Tracker/NewIrregularEventViewController.swift
> +        setupConstraints()
При пустом поле "name" проверки и блокировки кнопки не происходит, необходимо здесь добавить:

checkFields()

2023-10-21 11:45 UTC, protos17 commented on Tracker/NewIrregularEventViewController.swift
> +        let tracker = Tracker(id: id!, name: name!, color: color!, emoji: emoji!, createdAt: Date(), schedule: [])
Еще одна причина вылета при нажатии на кнопку "Создать" - принудительное извлечение опционалов. Рекомендую избавиться от этого, добавив проверку, что данные есть

2023-10-21 11:45 UTC, protos17 commented on Tracker/NewHabitViewController.swift
> +    private lazy var nameTrackerTextField: UITextField = {
Свойства принято писать раньше методов

2023-10-21 11:45 UTC, protos17 commented on Tracker/NewHabitViewController.swift
> +        let tracker = Tracker(id: id!, name: name!, color: color!, emoji: emoji!, createdAt: Date(), schedule: schedule!)
Не рекомендую использовать принудительное извлечение опционалов, лучше добавить проверку на guard let или if let

2023-10-21 11:45 UTC, protos17 commented on Tracker/TrackerUIViewCollectionCell.swift
> +    @objc func countButtonTapped() {
Рекомендую указать как private

2023-10-22 10:47 UTC, protos17 approved these changes

2023-10-22 10:47 UTC, protos17 commented on Tracker/CategoryViewController.swift
> +
С этим я полностью согласен, но в рамках обучения мы даем разные рекомендации, которые будут полезны в будущем и на функциональность не влияют. Данная рекомендация о порядке расположения свойств и методов повышает читаемость кода и его несоблюдение на код-ревью на реальной работе приведет к реджекту и отправке на доработку. Это требование не является обязательной, просто рекомендация по улучшению кода

2023-10-22 10:47 UTC, protos17 commented on Tracker/NewHabitViewController.swift
> +
Не обязательно это писать в каждом файле, рекомендую убрать везде, где добавлены эти комментарии

2023-10-24 16:30 UTC, dsiberia9s commented
OK

2023-10-24 16:30 UTC, merged